### PR TITLE
Fix textUi bug

### LINKED ISSUE #154: change app name and update UH, expected.txt

### LINKED ISSUE #155: truncate character in UI
use a truncator so that even if storage file is messed around, the UI remains correct

### PR DESCRIPTION
**Pull request by limwenfeng**

### CODE REVIEW

**Comment by limwenfeng** [comment]
Fixes #155 
Fixes #154

File: src/main/java/seedu/duke/ui/TextUi.java [hunk 1]
```diff
@@ -82,54 +84,60 @@ private void printList(List<Person> persons) {
...
 
     private void printPersonsInListWithStatus(List<Person> persons) {
         for (int i = 0; i < persons.size(); ++i) {
             Person personSelected = persons.get(i);
             String name = personSelected.getName().getNameString();
+            String truncatedName = nameTruncator(name);
             String idString = personSelected.getId().getIdString();
             String phoneString = (personSelected.getPhone().isAvailable())
-                    ? "--" : personSelected.getPhone().getPhoneNo();
+                    ? personSelected.getPhone().getPhoneNo() : "--";
```
Comment (sarzorwyn) [inline src/main/java/seedu/duke/ui/TextUi.java:130]: since you use this a lot, perhaps you can abstract out to a method and use if condition in that method for readability.

File: text-ui-test/EXPECTED.TXT [hunk 2]
```diff
@@ -1,8 +1,8 @@
-=========================================================
-Welcome to Safest Entry Tracker - Version v1.0
+============================================================================
+Welcome to Control Your Crowd - Version v2.0
```
Comment (sarzorwyn) [inline text-ui-test/EXPECTED.TXT:2]: v2 👏👏👏

File: src/main/java/seedu/duke/ui/TextUi.java [hunk 3]
```diff
@@ -11,15 +11,15 @@
...
+    public static final String PRINT_LISTALL_FORMAT = "|%-3s||%-35s||%-8s||%-10s||%-10s|";
+    public static final String PRINT_LIST_FORMAT =  "|%-3s||%-36s||%-12s||%-17s|";
 
     private final PrintStream out;
     private final Scanner in;
     private static final Logger logger = Logger.getLogger(TextUi.class.getSimpleName());
 
-    private static final String DIVIDER = "=".repeat(57);
-    private static final String SINGLE_DIVIDER = "-".repeat(57);
+    private static final String DIVIDER = "=".repeat(76);
```
Comment (sarzorwyn) [inline src/main/java/seedu/duke/ui/TextUi.java:21]: maybe a short comment to let the reader know 76 is the length of the divider or using a static final int
